version: '3.8'

services:
  live2d-api:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./model:/app/model
      - ./logs:/app/logs
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - JAVA_OPTS=-Xms512m -Xmx1024m
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/api/get?id=1"]
      interval: 30s
      timeout: 10s
      retries: 3