server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: live2d-api
  profiles:
    active: dev

# Live2D 配置
live2d:
  model:
    path: model  # 模型文件路径，相对于项目根目录

# 日志配置
logging:
  level:
    com.live2d.api: DEBUG
    org.springframework: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/live2d-api.log

# 管理端点配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always